[pytest]
pythonpath = src/python

testpaths = tests

python_files = test_*.py *_test.py
python_classes = Test*
python_functions = test_* teste_*

addopts =
    -v
    --tb=short
    --strict-markers
    --cov=src/python
    --cov-report=term-missing
    --cov-report=xml:coverage.xml

    