[pytest]
pythonpath = src/python

# Onde ficam os testes
testpaths = tests

# Padrão de arquivos de teste
python_files = test_*.py *_test.py
python_classes = Test*
python_functions = test_*

# Saída detalhada + cores no terminal
addopts =
    -v
    --tb=short
    --strict-markers
    --cov=src/python
    --cov-report=term-missing
    --cov-report=xml:coverage.xml