sonar.projectKey=rafaelmaia-dev_calculadora-while
sonar.organization=rafaelmaia-dev
sonar.host.url=https://sonarcloud.io

sonar.python.coverage.reportPaths=coverage.xml
sonar.sources=src
sonar.coverage.exclusions=src/python/calculadora.py
sonar.tests=tests


